### ISSUE TITLE
Possible subsetting bug in nest_filter_balance.R

### ISSUE THREAD

**Issue by DarwinAwardWinner** [myles-lewis/nestedcv#19]
In `nest_filt_bal`, some subsetting occurs, but the subsetting operation for `xtrain` on [line 15](https://github.com/myles-lewis/nestedcv/blob/main/R/nest_filter_balance.R#L15) appears to be missing a `drop = FALSE` as seen 2 lines later for `xtest`.

**Comment by myles-lewis** [comment]
Hi Ryan,
Thanks. The `drop = FALSE` for `xtest` is necessary for LOOCV or if `n_outer_folds` is high. But the outer training data continues all data except the test fold. So this issue is never going to occur in practise unless you had a tiny dataset of n=3 and n_outer_folds=2 which would be unsuitable for real analysis. Did you have an example or reprex where this issue generated an error? I don't mind adding `drop = FALSE` for `xtrain`, but in practise it's never going to be invoked.
Regards,
Myles

**Comment by DarwinAwardWinner** [comment]
No, I don't have a real-world example, and you're correct that it will likely never be a problem in practice. This was just an issue I noticed while reading the code. However, it's still something that could easily happen if the user calls the function with the wrong input, and in that case it would likely generate a very confusing error message relating to a downstream function expecting a matrix and receiving a vector, instead of the more informative error message that it should actually generate. So I think it's always worth getting indexing technically correct in cases like this.

By the way, the reason I was reading this code in the first place is because I'm trying to implement nested grouped CV (e.g. we have 100 subjects with a variable number of data points per subject, and samples from the same subject must always be grouped together and assigned to the same folds in both outer and inner CV). Please let me know if you would be interested in incorporating code for this into the nestedcv package, assuming I can get it working. Because it currently requires hacking a bunch of the package internals in order to send the grouping variable everywhere that x and y go.

**Comment by myles-lewis** [comment]
That's fine. I will change the code to add `drop = F` in the next update.

Interesting idea about the grouped CV. The way I would do this is to include the grouping column in `x` rather than adding a column to `y` (if your model needs it). Then I would create the folds manually and pass them into either `nestcv.glmnet()` or `nestcv.train()`. Then the rest of the code will stay the same and the model should fit fine. It depends if the model needs to know the grouping variable. Are you trying to use `nestcv.glmnet()` or `nestcv.train()`?

I don't mind coming up with some simple code to provide custom folds with a grouping variable. This would bypass caret's `createFolds()` command. It would need a bit of modification if you wanted the folds to balance the outcome as caret does.

I started work on cox version of glmnet which requires y to be a matrix with 2 columns. It's available in the branch `cox-glmnet`, see file `nestcv.coxnet`. But I removed the filter and balancing as this did not make sense in the context of cox regression and would be difficult to implement. I stopped on work on it as it was not clear to me that nested CV for cox models was statistically sound when combining the results and measuring performance on the outer folds since multiple Cox models had been fitted.

**Comment by DarwinAwardWinner** [comment]
I've already written a good bit of code, including functions to generate CV folds for any combination of grouped, stratified, and repeated, as well as an ugly hack of the nestedcv code to use a custom summaryFunction that receives the grouping variable so that it can evaluate each subject separately (our performance metric is correct ordering of samples within each subject). This requires using the recipe interface to `caret::train`, which means I have to rewrite a bunch of the internals of `nestcv.train` and the various functions it calls. It's kind of a mess, but I think I almost have it working.

**Comment by myles-lewis** [comment]
Ok, good luck!

I guess I would have just left it passing `y` as a vector, but passed in custom "grouped" folds using the `outer_folds` argument. Then I would have passed the group as a column in `x` and made a custom summaryFunction for caret in which the grouping column was pre-specified e.g. as `.group` as per caret notation. Then I'd have pulled the final results manually out of `outer_result` to calculate custom overall performance.
