### ISSUE TITLE
nestcv.glmnet with custom filter fails

### ISSUE THREAD

**Issue by frnkmxwll** [myles-lewis/nestedcv#37]
Error:
Performing 2-fold outer CV, using 1 core
Error in if (any(penalty.factor == Inf)) { : 
  missing value where TRUE/FALSE needed

I identified the bug and resolved it by replacing the else statement in nest_filter_balance.R, line 30 with:
```
else {
    args <- list(y = ytrain, x = xtrain)
    args <- append(args, filter_options)
    fset <- do.call(filterFUN, args)
    filt_xtrain <- xtrain[, fset, drop = FALSE]
    filt_xtest <- xtest[, fset, drop = FALSE]
    
    # Match indices of filtered set with original features
    fset_indices <- match(fset, colnames(x))
    filt_pen.factor <- penalty.factor[fset_indices]
```

Pretty sure the issue was that you were filtering on the gene names outputted by the custom filter, rather than their indexes.

Cheers,

**Comment by myles-lewis** [comment]
Actually, the internal filters written for the nestedcv packages all return an index and not column names. So your custom filter should not return column names, but it ought to return indices instead. Your `match()` lines of code need to be embedded at the end of your custom filter function so that your filter function returns an index vector.

**Comment by frnkmxwll** [comment]
Ah, fair enough, perhaps it would be good to update this part of the documentation in this case?
![image](https://github.com/myles-lewis/nestedcv/assets/1188958/0f5921e9-4a18-4310-8437-791955803528)

Love the package.

**Comment by myles-lewis** [comment]
Good spot, thank you! Updated now.
